name: CircleCI
version: 2.1

variables:
 - name: projectName
   value: CFD2021Projects

orbs:
  codecov: codecov/codecov@1.0.2 # need to allow 3rd party orbs in project settings on circleci
  python: circleci/python@0.2.1
jobs:
  build:
    working_directory: /root/project/CFD2021Projects   # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.6                # image comes from Docker hub
    steps:
      - checkout
      - run:
          name: Install and Test this package
          command: julia -e  'using Pkg; Pkg.activate(pwd()); Pkg.update(); Pkg.build(); Pkg.test(; coverage=true);'
      - env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run:
          name: Process and uplode code-coverage
          command: julia -e 'using Pkg; Pkg.activate(pwd()); using Coverage; Codecov.submit_local(process_folder())'
      - run:
          name: Process code-coverage
          command: julia -e 'using Pkg; Pkg.activate(pwd()); using Coverage; coverage = process_folder(); LCOV.writefile("coverage-lcov.info", coverage)'
      - codecov/upload:
          file: "coverage-lcov.info"
          token: ${{CODECOV_TOKEN}}

# version: 2.1

# orbs:
#   python: circleci/python@0.2.1

# jobs:
#   build-and-test:
#     executor: python/default
#     steps:
#       - checkout
#       - python/load-cache
#       - python/install-deps
#       - python/save-cache
#       - run:
#           command: ./manage.py test
#           name: Test

# workflows:
#   main:
#     jobs:
#       - build-and-test
